name: Build and Deploy Zola

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Install Zola
        run: |
          curl -sSf https://sh.rustup.rs | sh -s -- -y
          source $HOME/.cargo/env
          cargo install zola

      - name: Build Zola Site
        run: zola build

      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public
