name: Build and Deploy Zola

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          submodules: recursive
      - uses: denoland/setup-deno@v2
        with:
          deno-version: v2.x
      - run: deno run --allow-read --allow-net --allow-env=SASS_PATH --allow-write=public_html main.ts
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./public_html
